name: wheels

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
      branches:
        description: 'branches tested'
        required: false
        default: 'main'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # linux x86
          - name: linux-x86_64
            runs-on: ubuntu-24.04
            cibw_archs_linux: x86_64

          # linux aarch64
          - name: linux-aarch64
            runs-on: ubuntu-24.04-arm
            cibw_archs_linux: aarch64

          # arm64 mac
          - name: macos-arm64
            runs-on: macos-15
            cibw_archs_macos: arm64
            brew_prefix: /opt/homebrew


    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels with cibuildwheel
        uses: pypa/cibuildwheel@v3.2.1
        with:
          output-dir: dist
        env:
          CIBW_BUILD: "cp311-* cp312-* cp313-* cp314-*"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs_linux }}
          CIBW_ARCHS_MACOS: ${{ matrix.cibw_archs_macos }}

          CIBW_BEFORE_ALL_LINUX: |
            bash -eux -c '
              if command -v yum >/dev/null 2>&1; then
                yum -y install bzip2-devel xz-devel zlib-devel libcurl-devel
              elif command -v dnf >/dev/null 2>&1; then
                dnf -y install bzip2-devel xz-devel zlib-devel libcurl-devel
              elif command -v microdnf >/dev/null 2>&1; then
                microdnf -y install bzip2-devel xz-devel zlib-devel libcurl-devel
              else
                echo "No supported package manager found" >&2
                exit 1
              fi
            '

          CIBW_BEFORE_ALL_MACOS: |
            brew update
            brew install xz libomp llvm

          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET=15.0
            PATH="${{ matrix.brew_prefix }}/opt/llvm/bin:$PATH"
            CC="${{ matrix.brew_prefix }}/opt/llvm/bin/clang"
            CXX="${{ matrix.brew_prefix }}/opt/llvm/bin/clang++"
            CPPFLAGS="-I${{ matrix.brew_prefix }}/opt/libomp/include"
            LDFLAGS="-L${{ matrix.brew_prefix }}/opt/libomp/lib -Wl,-rpath,${{ matrix.brew_prefix }}/opt/libomp/lib"

      - if: matrix.name == 'linux-x86_64'
        name: Build source distribution
        run: |
          python -m pip install --upgrade build
          python -m build --sdist -o dist

      - name: Upload wheels & sdist
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.name }}
          path: dist/*

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          merge-multiple: true

      - name: Publish to PyPI (OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
          skip-existing: true
